//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordGuessingGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordGuessingGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alligator
        ///ant
        ///bear
        ///bee
        ///camel
        ///cat
        ///cheetah
        ///chicken
        ///chimpanzee
        ///cow
        ///crocodile
        ///deer
        ///dog
        ///dolphin
        ///duck
        ///eagle
        ///elephant
        ///fish
        ///fly
        ///fox
        ///frog
        ///giraffe
        ///goat
        ///goldfish
        ///hamster
        ///hippopotamus
        ///horse
        ///kangaroo
        ///kitten
        ///lion
        ///lobster
        ///monkey
        ///octopus
        ///owl
        ///panda
        ///pig
        ///puppy
        ///rabbit
        ///rat
        ///scorpion
        ///seal
        ///shark
        ///sheep
        ///snail
        ///snake
        ///spider
        ///squirrel
        ///tiger
        ///turtle
        ///wolf
        ///zebra.
        /// </summary>
        internal static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crow
        ///Peacock
        ///Dove
        ///Sparrow
        ///Goose
        ///Ostrich
        ///Pigeon
        ///Turkey
        ///Hawk
        ///Bald eagle
        ///Raven
        ///Parrot
        ///Flamingo
        ///Seagull
        ///Swallow
        ///Blackbird
        ///Penguin
        ///Robin
        ///Swan
        ///Owl
        ///Stork
        ///Woodpecker.
        /// </summary>
        internal static string Birds {
            get {
                return ResourceManager.GetString("Birds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen
        ///Helium
        ///lithium
        ///beryllium
        ///boron
        ///carbon
        ///nitrogen
        ///oxygen
        ///fluorine
        ///neon
        ///sodium
        ///magnesium
        ///Silicon
        ///Phosphorus
        ///Sulphur
        ///Chlorine
        ///Argon
        ///Potassium
        ///Calcium
        ///Scandium
        ///Titanium
        ///Chromium
        ///Maganese
        ///Iron
        ///Cobalt
        ///Nickel
        ///Copper
        ///Zinc
        ///Gallium
        ///Germanium
        ///Arsenic
        ///Selenium
        ///Bromine
        ///Krypton
        ///Rhodium
        ///Palladium
        ///Silver
        ///Cadmium
        ///Indium
        ///Tin
        ///Antimony
        ///Iodine
        ///Xenon
        ///Caesium
        ///Barium
        ///Cerium
        ///Platinum
        ///Gold
        ///Mercury
        ///Thallium
        ///Lead
        ///Bismuth
        ///Polonium
        ///Astatine
        ///Radon
        ///Francium
        ///Radium
        ///Actinium
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apples, Apricots, Avocados,
        ///Bananas, Boysenberries, Blueberries, Bing Cherry,Cherries, Cantaloupe, Crab apples, Clementine, Cucumbers,
        ///Damson plum, Dinosaur Eggs (Pluots), Dates, Dewberries, Dragon Fruit,
        ///Elderberry, Eggfruit, Evergreen Huckleberry, Entawak,
        ///Fig, Farkleberry, Finger Lime,
        ///Grapefruit, Grapes, Gooseberries, Guava
        ///Honeydew melon, Hackberry, Honeycrisp Apples
        ///Indian Prune (Plum), Indonesian Lime, Imbe, Indian Fig
        ///Jackfruit, Java Apple, Jambolan
        ///Kiwi, Kaffir Lime, Kumquat
        ///Lime (Lemon), [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fruits {
            get {
                return ResourceManager.GetString("Fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman {
            get {
                object obj = ResourceManager.GetObject("hangman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap q_mark {
            get {
                object obj = ResourceManager.GetObject("q mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beans
        ///Carrots
        ///Cauliflower
        ///Cabbages
        ///Capsicums
        ///Celery
        ///Chokos
        ///Cucumber
        ///Eggplant
        ///Garlic
        ///Ginger
        ///Lettuce
        ///Mushrooms
        ///Okra
        ///Onions
        ///Peas
        ///Potatoes
        ///Puha
        ///Pumpkins
        ///Spinach
        ///Corn
        ///Tomatoes
        ///Turnip
        ///Yams
        ///.
        /// </summary>
        internal static string Vegetables {
            get {
                return ResourceManager.GetString("Vegetables", resourceCulture);
            }
        }
    }
}
